import { canonicalizeJcs, ContractError, hashJcs } from "./jcs.js";

const PURPOSE = "invoice_template_proposal";
const CLASSES = new Set(["label", "date", "amount", "quantity", "description", "structural-header", "other-opaque"]);
const RELATION_KEYS = { ROW_MEMBER: ["kind", "rowId", "tokenId", "ordinal"], COLUMN_MEMBER: ["kind", "columnId", "tokenId", "ordinal"], HEADER_FOR_COLUMN: ["kind", "headerTokenId", "columnId"], LABEL_FOR_VALUE: ["kind", "labelTokenId", "valueTokenId"], NEXT_IN_READING_ORDER: ["kind", "fromTokenId", "toTokenId"], REPEATED_HEADER_OF: ["kind", "repeatedRowId", "canonicalRowId"] };
const PAGE_RELATIONS = new Set(["ANY_PAGE", "FIRST_PAGE", "SAME_PAGE_AS_TARGET", "PRIOR_PAGE"]);
const TOKEN = /^t_[0-9a-f]{16}$/; const GROUP = /^g_[0-9a-f]{16}$/; const MATCHING_KEY = /^sup_[0-9a-f]{32}$/; const SHA256 = /^[0-9a-f]{64}$/; const TX = /^tx_[0-9a-f]{32}$/; const DOC = /^[A-Za-z0-9_-]{22}$/; const ACTION = /^act_[0-9a-f]{32}$/; const POLICY = /^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$/; const TIMESTAMP = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/;
const own = (object, key) => Object.prototype.hasOwnProperty.call(object, key);
const fail = (reason) => { throw new ContractError("semantic_invalid", reason); };
const exact = (value, keys) => value && typeof value === "object" && !Array.isArray(value) && Object.keys(value).length === keys.length && keys.every((key) => own(value, key));
const integer = (value, min, max) => Number.isSafeInteger(value) && value >= min && value <= max;
const pattern = (value, regex, reason) => { if (typeof value !== "string" || !regex.test(value)) fail(reason); };
function timestamp(value) { pattern(value, TIMESTAMP, "INVALID_TIMESTAMP"); const date = new Date(value); if (Number.isNaN(date.getTime()) || date.toISOString() !== value) fail("INVALID_TIMESTAMP"); }
function rect(value) { if (!exact(value, ["x", "y", "width", "height"]) || !integer(value.x, 0, 10000) || !integer(value.y, 0, 10000) || !integer(value.width, 1, 10000) || !integer(value.height, 1, 10000) || value.x + value.width > 10000 || value.y + value.height > 10000) fail("INVALID_GEOMETRY"); }

function checkProjection(value) {
  if (!exact(value, ["projectionSchemaVersion", "tokens", "groups", "relationships", "counts"]) || value.projectionSchemaVersion !== "1" || !Array.isArray(value.tokens) || value.tokens.length < 1 || value.tokens.length > 4096 || !Array.isArray(value.groups) || value.groups.length < 1 || value.groups.length > 8192 || !Array.isArray(value.relationships) || value.relationships.length > 8192 || !exact(value.counts, ["pageCount", "tokenCount", "groupCount", "relationshipCount"])) fail("PROJECTION_SHAPE");
  const tokenIds = new Set(); for (const token of value.tokens) { if (!exact(token, ["opaqueId", "semanticClass", "page", "normalizedRect"])) fail("TOKEN_SHAPE"); pattern(token.opaqueId, TOKEN, "INVALID_TOKEN_ID"); if (tokenIds.has(token.opaqueId)) fail("DUPLICATE_PROJECTION_ID"); tokenIds.add(token.opaqueId); if (!CLASSES.has(token.semanticClass) || !integer(token.page, 1, 100)) fail("INVALID_TOKEN"); rect(token.normalizedRect); }
  const groupById = new Map(); for (const group of value.groups) { if (!exact(group, ["groupId", "kind", "page", "ordinal"])) fail("GROUP_SHAPE"); pattern(group.groupId, GROUP, "INVALID_GROUP_ID"); if (groupById.has(group.groupId)) fail("DUPLICATE_PROJECTION_ID"); groupById.set(group.groupId, group); if (!["ROW", "COLUMN"].includes(group.kind) || !integer(group.page, 1, 100) || !integer(group.ordinal, 0, 4095)) fail("INVALID_GROUP"); }
  if (!integer(value.counts.pageCount, 1, 100) || value.counts.tokenCount !== value.tokens.length || value.counts.groupCount !== value.groups.length || value.counts.relationshipCount !== value.relationships.length) fail("PROJECTION_COUNT_MISMATCH");
  const pages = [...value.tokens, ...value.groups].map(({ page }) => page); if (Math.max(...pages) !== value.counts.pageCount) fail("PROJECTION_PAGE_COUNT_MISMATCH");
  const edges = new Set(); const next = new Map();
  for (const edge of value.relationships) {
    const keys = RELATION_KEYS[edge?.kind]; if (!keys || !exact(edge, keys)) fail("RELATIONSHIP_SHAPE");
    const edgeKey = canonicalizeJcs(edge); if (edges.has(edgeKey)) fail("DUPLICATE_RELATIONSHIP"); edges.add(edgeKey);
    const tokenRefs = [edge.tokenId, edge.headerTokenId, edge.labelTokenId, edge.valueTokenId, edge.fromTokenId, edge.toTokenId].filter((id) => id !== undefined); const groupRefs = [edge.rowId, edge.columnId, edge.repeatedRowId, edge.canonicalRowId].filter((id) => id !== undefined);
    tokenRefs.forEach((id) => { pattern(id, TOKEN, "INVALID_TOKEN_ID"); if (!tokenIds.has(id)) fail("MISSING_RELATIONSHIP_REFERENCE"); }); groupRefs.forEach((id) => { pattern(id, GROUP, "INVALID_GROUP_ID"); if (!groupById.has(id)) fail("MISSING_RELATIONSHIP_REFERENCE"); });
    if (edge.ordinal !== undefined && !integer(edge.ordinal, 0, 4095)) fail("INVALID_RELATIONSHIP_ORDINAL");
    if (edge.kind === "ROW_MEMBER" && groupById.get(edge.rowId).kind !== "ROW") fail("ROW_REFERENCE_KIND");
    if (["COLUMN_MEMBER", "HEADER_FOR_COLUMN"].includes(edge.kind) && groupById.get(edge.columnId).kind !== "COLUMN") fail("COLUMN_REFERENCE_KIND");
    if (edge.kind === "LABEL_FOR_VALUE" && edge.labelTokenId === edge.valueTokenId || edge.kind === "NEXT_IN_READING_ORDER" && edge.fromTokenId === edge.toTokenId || edge.kind === "REPEATED_HEADER_OF" && edge.repeatedRowId === edge.canonicalRowId) fail("RELATIONSHIP_SELF_EDGE");
    if (edge.kind === "NEXT_IN_READING_ORDER") next.set(edge.fromTokenId, edge.toTokenId);
    if (edge.kind === "REPEATED_HEADER_OF") { const repeated = groupById.get(edge.repeatedRowId); const canonical = groupById.get(edge.canonicalRowId); if (repeated.kind !== "ROW" || canonical.kind !== "ROW" || canonical.page > repeated.page || canonical.page === repeated.page && canonical.ordinal >= repeated.ordinal) fail("REPEATED_HEADER_ORDER"); }
  }
  for (const start of next.keys()) { const seen = new Set(); let cursor = start; while (next.has(cursor)) { if (seen.has(cursor)) fail("RELATIONSHIP_CYCLE"); seen.add(cursor); cursor = next.get(cursor); } }
  return value;
}

export function projectionHashInput(value) { const fullKeys = ["projectionSchemaVersion", "templateSchemaVersion", "proposalResponseSchemaVersion", "purpose", "transactionId", "documentId", "projectionSha256", "matchingKey", "providerId", "modelId", "policyVersion", "disclosureVersion", "expiresAt", "tokens", "groups", "relationships", "counts"]; const full = value?.purpose === PURPOSE; if (full && !exact(value, fullKeys)) fail("UNKNOWN_FIELD"); const source = full ? { projectionSchemaVersion: value.projectionSchemaVersion, tokens: value.tokens, groups: value.groups, relationships: value.relationships, counts: value.counts } : value; const keys = ["projectionSchemaVersion", "tokens", "groups", "relationships", "counts"]; if (!exact(source, keys)) fail("UNKNOWN_FIELD"); return checkProjection(source); }
export function hashProjection(value) { return hashJcs(projectionHashInput(value)); }

export function buildProposalProjection(input) {
  const keys = ["projection", "transactionId", "documentId", "matchingKey", "providerId", "modelId", "policyVersion", "disclosureVersion", "expiresAt"]; if (!exact(input, keys)) fail("UNKNOWN_FIELD"); const projection = projectionHashInput(input.projection);
  pattern(input.transactionId, TX, "INVALID_TRANSACTION_ID"); pattern(input.documentId, DOC, "INVALID_DOCUMENT_ID"); pattern(input.matchingKey, MATCHING_KEY, "INVALID_MATCHING_KEY"); ["providerId", "modelId", "policyVersion", "disclosureVersion"].forEach((name) => pattern(input[name], POLICY, "INVALID_POLICY_ID")); timestamp(input.expiresAt);
  const result = { projectionSchemaVersion: "1", templateSchemaVersion: "1", proposalResponseSchemaVersion: "1", purpose: PURPOSE, transactionId: input.transactionId, documentId: input.documentId, projectionSha256: hashJcs(projection), matchingKey: input.matchingKey, providerId: input.providerId, modelId: input.modelId, policyVersion: input.policyVersion, disclosureVersion: input.disclosureVersion, expiresAt: input.expiresAt, tokens: projection.tokens, groups: projection.groups, relationships: projection.relationships, counts: projection.counts }; validateProposalProjection(result); return result;
}

export function validateProposalProjection(value) { const keys = ["projectionSchemaVersion", "templateSchemaVersion", "proposalResponseSchemaVersion", "purpose", "transactionId", "documentId", "projectionSha256", "matchingKey", "providerId", "modelId", "policyVersion", "disclosureVersion", "expiresAt", "tokens", "groups", "relationships", "counts"]; if (!exact(value, keys) || value.projectionSchemaVersion !== "1" || value.templateSchemaVersion !== "1" || value.proposalResponseSchemaVersion !== "1" || value.purpose !== PURPOSE) fail("PROPOSAL_SHAPE"); pattern(value.transactionId, TX, "INVALID_TRANSACTION_ID"); pattern(value.documentId, DOC, "INVALID_DOCUMENT_ID"); pattern(value.projectionSha256, SHA256, "INVALID_PROJECTION_HASH"); pattern(value.matchingKey, MATCHING_KEY, "INVALID_MATCHING_KEY"); ["providerId", "modelId", "policyVersion", "disclosureVersion"].forEach((name) => pattern(value[name], POLICY, "INVALID_POLICY_ID")); timestamp(value.expiresAt); projectionHashInput(value); if (value.projectionSha256 !== hashProjection(value)) fail("PROJECTION_HASH_MISMATCH"); return true; }

export function geometryBucket(value, role) { rect(value); if (!["FIELD_LABEL", "TABLE_HEADER", "TABLE_BOUNDARY"].includes(role)) fail("INVALID_GEOMETRY_ROLE"); const bucket = (number) => Math.min(100, Math.floor(number / 100)); return { role, x: bucket(value.x), y: bucket(value.y), width: bucket(value.width), height: bucket(value.height) }; }
export function buildLayoutStructureProjection(input) {
  const keys = ["fieldLabelGeometryBuckets", "tableColumnGeometryBuckets", "fieldLabelPageRelations", "tableColumnPageRelations", "repeatedHeaderSignature"]; if (!exact(input, keys) || !Array.isArray(input.fieldLabelGeometryBuckets) || !Array.isArray(input.tableColumnGeometryBuckets) || !Array.isArray(input.fieldLabelPageRelations) || !Array.isArray(input.tableColumnPageRelations) || input.fieldLabelGeometryBuckets.length !== 7 || input.tableColumnGeometryBuckets.length !== 3 || input.fieldLabelPageRelations.length !== 7 || input.tableColumnPageRelations.length !== 3 || !exact(input.repeatedHeaderSignature, ["repeatedHeaderPolicy"]) || !["REQUIRED", "ABSENT"].includes(input.repeatedHeaderSignature.repeatedHeaderPolicy)) fail("INVALID_LAYOUT_STRUCTURE");
  const roles = [...Array(7).fill("FIELD_LABEL"), "TABLE_HEADER", "TABLE_HEADER", "TABLE_BOUNDARY"]; [...input.fieldLabelGeometryBuckets, ...input.tableColumnGeometryBuckets].forEach((bucket, index) => { if (!exact(bucket, ["role", "x", "y", "width", "height"]) || bucket.role !== roles[index] || [bucket.x, bucket.y, bucket.width, bucket.height].some((number) => !integer(number, 0, 100))) fail("INVALID_GEOMETRY_BUCKET"); }); if ([...input.fieldLabelPageRelations, ...input.tableColumnPageRelations].some((relation) => !PAGE_RELATIONS.has(relation))) fail("INVALID_PAGE_RELATION");
  return { invoiceEvidenceSchemaVersion: "1", templateSchemaVersion: "1", executionPolicyVersion: "1", fieldLabelGeometryBuckets: input.fieldLabelGeometryBuckets, tableColumnGeometryBuckets: input.tableColumnGeometryBuckets, fieldLabelPageRelations: input.fieldLabelPageRelations, tableColumnPageRelations: input.tableColumnPageRelations, repeatedHeaderSignature: input.repeatedHeaderSignature, columnOrder: ["description", "quantity", "unitPrice"] };
}
export const hashLayoutStructure = (value) => { if (value?.invoiceEvidenceSchemaVersion === "1") { if (!exact(value, ["invoiceEvidenceSchemaVersion", "templateSchemaVersion", "executionPolicyVersion", "fieldLabelGeometryBuckets", "tableColumnGeometryBuckets", "fieldLabelPageRelations", "tableColumnPageRelations", "repeatedHeaderSignature", "columnOrder"]) || value.templateSchemaVersion !== "1" || value.executionPolicyVersion !== "1" || canonicalizeJcs(value.columnOrder) !== '["description","quantity","unitPrice"]') fail("INVALID_LAYOUT_STRUCTURE"); return hashJcs(buildLayoutStructureProjection({ fieldLabelGeometryBuckets: value.fieldLabelGeometryBuckets, tableColumnGeometryBuckets: value.tableColumnGeometryBuckets, fieldLabelPageRelations: value.fieldLabelPageRelations, tableColumnPageRelations: value.tableColumnPageRelations, repeatedHeaderSignature: value.repeatedHeaderSignature })); } return hashJcs(buildLayoutStructureProjection(value)); };
export function proposalScopeKey(input) { if (!exact(input, ["matchingKey", "layoutStructureHash"])) fail("INVALID_SCOPE_INPUT"); pattern(input.matchingKey, MATCHING_KEY, "INVALID_MATCHING_KEY"); pattern(input.layoutStructureHash, SHA256, "INVALID_LAYOUT_HASH"); return hashJcs({ matchingKey: input.matchingKey, layoutStructureHash: input.layoutStructureHash, purpose: PURPOSE }); }

export function buildPreparedBindingInput(input) {
const keys = ["transactionId", "documentSha256", "projectionSha256", "matchingKey", "proposalScopeKey", "providerId", "modelId", "policyVersion", "disclosureVersion", "expiresAt", "consentActionId"]; const source = { ...input, consentActionId: input?.consentActionId ?? null }; if (!exact(source, keys)) fail("INVALID_BINDING_INPUT"); pattern(source.transactionId, TX, "INVALID_TRANSACTION_ID"); ["documentSha256", "projectionSha256", "proposalScopeKey"].forEach((name) => pattern(source[name], SHA256, "INVALID_BINDING_HASH")); pattern(source.matchingKey, MATCHING_KEY, "INVALID_MATCHING_KEY"); ["providerId", "modelId", "policyVersion", "disclosureVersion"].forEach((name) => pattern(source[name], POLICY, "INVALID_POLICY_ID")); timestamp(source.expiresAt); if (source.consentActionId !== null) pattern(source.consentActionId, ACTION, "INVALID_CONSENT_ACTION");
  return { proposalResponseSchemaVersion: "1", transactionId: source.transactionId, documentSha256: source.documentSha256, projectionSha256: source.projectionSha256, purpose: PURPOSE, matchingKey: source.matchingKey, proposalScopeKey: source.proposalScopeKey, providerId: source.providerId, modelId: source.modelId, policyVersion: source.policyVersion, disclosureVersion: source.disclosureVersion, consentActionId: source.consentActionId, expiresAt: source.expiresAt, oneUseBudget: "ONE_PROVIDER_ATTEMPT" };
}
export const hashPreparedBinding = (value) => { const keys = ["proposalResponseSchemaVersion", "transactionId", "documentSha256", "projectionSha256", "purpose", "matchingKey", "proposalScopeKey", "providerId", "modelId", "policyVersion", "disclosureVersion", "consentActionId", "expiresAt", "oneUseBudget"]; if (exact(value, keys)) { if (value.proposalResponseSchemaVersion !== "1" || value.purpose !== PURPOSE || value.oneUseBudget !== "ONE_PROVIDER_ATTEMPT") fail("INVALID_BINDING_INPUT"); buildPreparedBindingInput({ transactionId: value.transactionId, documentSha256: value.documentSha256, projectionSha256: value.projectionSha256, matchingKey: value.matchingKey, proposalScopeKey: value.proposalScopeKey, providerId: value.providerId, modelId: value.modelId, policyVersion: value.policyVersion, disclosureVersion: value.disclosureVersion, expiresAt: value.expiresAt, consentActionId: value.consentActionId }); return hashJcs(value); } return hashJcs(buildPreparedBindingInput(value)); };
export function buildProposalDisclosure(input) { const keys = ["providerId", "modelId", "policyVersion", "disclosureVersion", "expiresAt"]; if (!exact(input, keys)) fail("INVALID_DISCLOSURE"); keys.slice(0, 4).forEach((name) => pattern(input[name], POLICY, "INVALID_POLICY_ID")); timestamp(input.expiresAt); return { proposalResponseSchemaVersion: "1", purpose: PURPOSE, providerId: input.providerId, modelId: input.modelId, policyVersion: input.policyVersion, disclosureVersion: input.disclosureVersion, expiresAt: input.expiresAt, allowedCategories: ["OPAQUE_MATCHING_KEY", "TOKEN_CLASSES", "NORMALIZED_GEOMETRY", "ROW_COLUMN_STRUCTURE"], egressCount: 0 }; }

export const createProposalProjection = buildProposalProjection;
export const hashProjectionInput = hashProjection;
export const buildProjectionHashInput = projectionHashInput;
export const projectionHash = hashProjection;
export const buildProposalScopeKey = proposalScopeKey;
export const buildLayoutStructureHash = hashLayoutStructure;
export const createPreparedBindingInput = buildPreparedBindingInput;
export const preparedBindingInput = buildPreparedBindingInput;
export const preparedBindingHash = hashPreparedBinding;
